version: '2'
jobs:
  build:
    working_directory: /go/src/github.com/archivers-space/archivers-api
    docker:
      - image: circleci/cci-demo-go-primary:0.0.2
        environment:
          GOLANG_ENV: test
          BASE_URL: localhost:3000
          PORT: 3000
          DEBUG: false
          POSTGRES_DB_URL: postgres://ubuntu:@localhost:5432/circle_test?sslmode=disable
      - image: postgres:9.6.2
        environment:
          POSTGRES_USER: ubuntu
          BOSTREAS_DB: circle_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run: mkdir -p $CIRCLE_TEST_REPORTS/archivers-space
      - run: go get -v github.com/jstemmer/go-junit-report
      - run: go-wrapper download && go-wrapper install
      - run: 
          name: go test
          command: go test -v -race ./... | tee $CIRCLE_TEST_REPORTS/archivers-space/original.txt ; test ${PIPESTATUS[0]} -eq 0
      - run: cat $CIRCLE_TEST_REPORTS/archivers-space/original.txt | go-junit-report > $CIRCLE_TEST_REPORTS/archivers-space/junit.xml
      - store_test_results:
          path: $CIRCLE_TEST_REPORTS/archivers-space/junit.xml